// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// crossprodCpp
SEXP crossprodCpp(SEXP A, SEXP B);
RcppExport SEXP _netgsa_crossprodCpp(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type A(ASEXP);
    Rcpp::traits::input_parameter< SEXP >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(crossprodCpp(A, B));
    return rcpp_result_gen;
END_RCPP
}
// matMult
SEXP matMult(SEXP A, SEXP B);
RcppExport SEXP _netgsa_matMult(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type A(ASEXP);
    Rcpp::traits::input_parameter< SEXP >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(matMult(A, B));
    return rcpp_result_gen;
END_RCPP
}
// solveCpp
SEXP solveCpp(SEXP A, SEXP B);
RcppExport SEXP _netgsa_solveCpp(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type A(ASEXP);
    Rcpp::traits::input_parameter< SEXP >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(solveCpp(A, B));
    return rcpp_result_gen;
END_RCPP
}
// cholCpp
SEXP cholCpp(SEXP A);
RcppExport SEXP _netgsa_cholCpp(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(cholCpp(A));
    return rcpp_result_gen;
END_RCPP
}
// pseudoinverseCpp
SEXP pseudoinverseCpp(SEXP A);
RcppExport SEXP _netgsa_pseudoinverseCpp(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(pseudoinverseCpp(A));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_netgsa_crossprodCpp", (DL_FUNC) &_netgsa_crossprodCpp, 2},
    {"_netgsa_matMult", (DL_FUNC) &_netgsa_matMult, 2},
    {"_netgsa_solveCpp", (DL_FUNC) &_netgsa_solveCpp, 2},
    {"_netgsa_cholCpp", (DL_FUNC) &_netgsa_cholCpp, 1},
    {"_netgsa_pseudoinverseCpp", (DL_FUNC) &_netgsa_pseudoinverseCpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_netgsa(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
