# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

crossprodCpp <- function(A, B = NULL) {
    .Call('_netgsa_crossprodCpp', PACKAGE = 'netgsa', A, B)
}

matMult <- function(A, B) {
    .Call('_netgsa_matMult', PACKAGE = 'netgsa', A, B)
}

solveCpp <- function(A, B = NULL) {
    .Call('_netgsa_solveCpp', PACKAGE = 'netgsa', A, B)
}

cholCpp <- function(A) {
    .Call('_netgsa_cholCpp', PACKAGE = 'netgsa', A)
}

pseudoinverseCpp <- function(A) {
    .Call('_netgsa_pseudoinverseCpp', PACKAGE = 'netgsa', A)
}

